### ISSUE TITLE
笑谱多账号，1账号完成后，后面的都无法继续

### ISSUE THREAD

**Issue by leave668** [ZhiYi-N/script#7]
笑谱多账号，1账号完成后，后面的都无法继续。

**Comment by ZhiYi-N** [comment]
好，我测试一下

**Comment by ZhiYi-N** [comment]
https://raw.githubusercontent.com/ZhiYi-N/Private-Script/master/Scripts/xp.js用这个试试，我自己测试没有问题，有问题的话去群组吧，issue不太方便https://t.me/hahaha8028
