### ISSUE TITLE
前几个会看到普通视频，后面一直看金蛋视频

### ISSUE THREAD

**Issue by kingsleyzhnlanf** [ZhiYi-N/script#9]
‘’‘’‘’‘’
🔔笑谱, 开始!
您选择的是用"#"隔开

============ 脚本执行-国际标准时间(UTC)：1/27/2021, 1:36:09 PM  =============

============ 脚本执行-北京时间(UTC+8)：1/27/2021, 9:36:09 PM  =============

------------- 共2个账号----------------

开始【笑谱1】
xpvideo4
1348692125288377515
xplive18
livesid:1348602411185672933
金币余额：18246
现金余额：1.88
📣看视频
获得58
📣看直播
获得500

开始【笑谱2】
xpvideo4
1348692125281527317
xplive18
livesid:1348602411185672300
金币余额：15317
现金余额：2.53
📣看视频
获得83
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo4
1348692125287707686
xplive19
livesid:1348602411185672639
金币余额：18804
现金余额：1.94
📣看视频
获得114
📣看直播
获得500

开始【笑谱2】
xpvideo4
1348692125286653068
xplive19
livesid:1348602411185672663
金币余额：15900
现金余额：2.59
📣看视频
获得115
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo5
1348692125284864448
xplive20
livesid:1348602411185672472
金币余额：19418
现金余额：2
📣看金蛋视频
获得106
📣看直播
获得500

开始【笑谱2】
xpvideo5
1348692125281723882
xplive20
livesid:1348602411185672492
金币余额：16515
现金余额：2.65
📣看金蛋视频
获得377
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo4
1348692125285346540
xplive21
livesid:13486024111856725
金币余额：20024
现金余额：2.06
📣看金蛋视频
获得387
📣看直播
获得500

开始【笑谱2】
xpvideo4
1348692125282567185
xplive21
livesid:1348602411185672338
金币余额：17392
现金余额：2.73
📣看金蛋视频
获得395
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125284638535
xplive22
livesid:1348602411185672942
金币余额：20911
现金余额：2.15
📣看金蛋视频
获得334
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125281189215
xplive22
livesid:1348602411185672864
金币余额：18287
现金余额：2.82
📣看金蛋视频
获得336
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125287585317
xplive23
livesid:1348602411185672996
金币余额：21745
现金余额：2.23
📣看金蛋视频
获得222
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125285487923
xplive23
livesid:1348602411185672359
金币余额：19123
现金余额：2.91
📣看金蛋视频
获得235
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125284872011
xplive24
livesid:1348602411185672376
金币余额：22467
现金余额：2.3
📣看金蛋视频
获得295
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125285411436
xplive24
livesid:1348602411185672218
金币余额：19858
现金余额：2.98
📣看金蛋视频
获得179
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125283026250
xplive25
livesid:1348602411185672512
金币余额：23262
现金余额：2.38
📣看金蛋视频
获得176
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125282442066
xplive25
livesid:134860241118567213
金币余额：20537
现金余额：3.05
📣看金蛋视频
获得103
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125282777462
xplive26
livesid:1348602411185672154
金币余额：23938
现金余额：2.45
📣看金蛋视频
获得185
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125284177881
xplive26
livesid:134860241118567283
金币余额：21140
现金余额：3.11
📣看金蛋视频
获得293
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125288853840
xplive27
livesid:1348602411185672126
金币余额：24623
现金余额：2.52
📣看金蛋视频
获得148
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125289615734
xplive27
livesid:1348602411185672941
金币余额：21933
现金余额：3.19
📣看金蛋视频
获得356
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125283794368
xplive28
livesid:1348602411185672777
金币余额：25271
现金余额：2.58
📣看金蛋视频
获得348
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125286468351
xplive28
livesid:1348602411185672206
金币余额：22789
现金余额：3.27
📣看金蛋视频
获得224
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125281451706
xplive29
livesid:1348602411185672315
金币余额：26119
现金余额：2.67
📣看金蛋视频
获得126
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125288868367
xplive29
livesid:1348602411185672761
金币余额：23513
现金余额：3.35
📣看金蛋视频
获得298
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125283922850
xplive30
livesid:1348602411185672107
金币余额：26745
现金余额：2.73
📣看金蛋视频
获得323
📣看直播
获得500

开始【笑谱2】
xpvideo3
1348692125283600472
xplive30
livesid:1348602411185672941
金币余额：24311
现金余额：3.43
📣看金蛋视频
获得303
📣看直播
⚠️异常直播活动红包已领

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125280297658
xplive31
livesid:1348602411185672788
金币余额：27568
现金余额：2.81
📣看金蛋视频
获得174
📣看直播
获得500

开始【笑谱2】
xpvideo2
1348692125288527837
xplive30
livesid:1348602411185672234
金币余额：24614
现金余额：3.46
📣看金蛋视频
获得250
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

------------- 共2个账号----------------

开始【笑谱1】
xpvideo3
1348692125280270883
xplive32
livesid:1348602411185672783
金币余额：28242
现金余额：2.88
📣看金蛋视频
获得315
📣看直播
获得500

开始【笑谱2】
xpvideo2
1348692125287163252
xplive31
livesid:1348602411185672865
金币余额：25364
现金余额：3.53
📣看金蛋视频
获得204
📣看直播
获得500

========================本次任务执行完毕，休息1分钟==============================

**Comment by ZhiYi-N** [comment]
这个有问题，我发现了，用private那个库里的吧

**Comment by kingsleyzhnlanf** [comment]
那个可以，谢谢大佬
